name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            setup.py
            requirements-dev.txt

      - name: Install package
        run: pip install .

      - name: Install dev requirements
        run: pip install -r requirements-dev.txt

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Run pytest
        run: pytest -Werror -s --block-network --cov pystac_client --cov-report term-missing

      - name: Run coverage
        run: coverage xml

      - name: Upload All coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false

  min-versions:
    name: min-versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "requirements-min.txt"
      - name: Install minimum requirements
        run: pip install -r requirements-min.txt
      - name: Install
        run: pip install .
      - name: Install dev requirements
        run: pip install -r requirements-dev.txt
      - name: Check minimum requirements
        run: scripts/check-minimum-requirements
      - name: Test
        run: ./scripts/test

  docs:
    name: docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "requirements-docs.txt"
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get -y install pandoc
      - name: Install docs requirements
        run: pip install -r requirements-docs.txt
      - name: Install pystac_client
        run: pip install .
      - name: Build docs
        run: ./scripts/build-docs

  pre-release:
    name: pre-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "setup.py"
      - name: Install
        run: pip install .
      - name: Install any pre-releases of pystac
        run: pip install -U --pre pystac
      - name: Install dev requirements
        run: pip install -r requirements-dev.txt
      - name: Test
        run: ./scripts/test

  dev-and-docs-requirements:
    name: dev and docs requirements check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
          cache-dependency-path: "setup.py"
      - name: Install
        run: pip install .
      - name: Install dev and docs requirements
        run: pip install -r requirements-dev.txt -r requirements-docs.txt
